# Generated by Django 5.1.5 on 2025-02-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['numbering'], 'verbose_name_plural': 'school'},
        ),
        migrations.AddField(
            model_name='school',
            name='numbering',
            field=models.IntegerField(default=0),
        ),
    ]
